# Generated by Django 5.0.4 on 2024-05-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='user_id',
        ),
    ]
