# Generated by Django 5.0.4 on 2024-05-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_rename_user_appointment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user',
        ),
    ]
