# Generated by Django 5.0.4 on 2024-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_rename_user_id_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
