# Generated by Django 5.0.4 on 2024-05-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_remove_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.TextField(max_length=50),
        ),
    ]
