# Generated by Django 5.0.4 on 2024-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_alter_appointment_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
