# Generated by Django 5.0.4 on 2024-05-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_alter_appointment_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.TextField(default=False, max_length=50),
        ),
    ]
