# Generated by Django 5.0.4 on 2024-05-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_alter_appointment_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
