# Generated by Django 5.0.4 on 2024-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_guardian_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='accepted',
            field=models.TextField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.TextField(default=False, max_length=50),
        ),
    ]
