# Generated by Django 5.0.4 on 2024-05-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0011_guardian_accepted_alter_appointment_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
