# Generated by Django 5.0.4 on 2024-05-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0012_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
